### ISSUE TITLE
Is the wind simulation working correctly? Directionless wind?

### ISSUE THREAD

**Issue by JLSievert** [grasbrook-cityscope/functionalscope#100]
The results of the wind simulations are looking funkier -- different than in the past. Almost as if the wind is directionless? (In both screenshots, wind should be coming from the west. 

![grafik](https://user-images.githubusercontent.com/45463490/145583815-4538cab5-fa64-4fca-ab26-19ff4d9007ae.png)

![grafik](https://user-images.githubusercontent.com/45463490/145583854-6c0a65d8-3045-4c46-8e1e-f8590ba68fb2.png)

**Comment by andredaa** [comment]
puh? that would be weird. i didnt hear of any updates from the api. i will check.

**Comment by andredaa** [comment]
So. I couldnt reproduce directionless wind. 
However - results seem to get mixed if we submit a new calculation request while we are waiting for all result tiles to come in.
Strangely: Those mixed results seem to come from the backend. So it seems the backend is caching the 2 requests under the same key. Potentially due to the front-end having started to post the calculation request over and over again. 
I would propose: I refactor front-end of wind first. then we see if the problem persists?

**Comment by andredaa** [comment]
#102 , this should solve the described issue.
